modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
    modId="rdpmouse"
    version="${version}"
    displayName="RDPMouse"
    authors="KesslerCascade"
    description="Fixes mouse look when playing over RDP (Remote Desktop Protocol), and allows camera rotation with the keyboard."

[[dependencies.rdpmouse]]
    modId="neoforge"
    type="required"
    versionRange="[26.1,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.rdpmouse]]
    modId="minecraft"
    type="required"
    versionRange="[26.2,)"
    ordering="NONE"
    side="BOTH"

[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"

[[mixins]]
    config="rdpmouse.mixins.json"
